TestAppCore/TestAppCore/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestAppCore.Models;

namespace TestAppCore.Controllers
{
    public class LoginController : Controller
    {
        private IPizzaManager _manager;

        public LoginController(IPizzaManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public IActionResult login()
        {
            return View("login");
        }

        [HttpPost]
        public IActionResult login(string inputUsername, string inputPassword)
        {
            ViewBag.manager = _manager;
            if (inputUsername.Equals("admin") && inputPassword.Equals("admin"))
            {
                ViewData["logged"] = true;
                return View("loginSuccess");
            }
            ViewData["logged"] = false;
            return View("loginFailed");
        }

        
        public IActionResult pizzaManager()
        {

            ViewBag.manager = _manager;
            return View("pizzamanager");
        }
        
        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "AABCDEEFGHIIJKLMNOOPQRSTUUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public IActionResult SimpleTable( TableInput option)
        {
            var count = _manager.getPizze().Count;

            List<Object[]> result = new List<object[]>();
            int max = option.length <= 10 ? 10 : option.length;
            max = max > count ? count : max;
            List<Pizza> ps = _manager.getSet(option.start, max);
            foreach (Pizza p in ps)
            {
                result.Add(new Object[] { p.Name, p.Description, p.Id });
            }

            return Json(new { draw = option.draw, data = result, recordsTotal = count, recordsFiltered = count });
        }

        [HttpPost]
        public IActionResult SimpleAjax( CRUD_ACTION m, Pizza model)
        {
           
            if (m != CRUD_ACTION.delete && !ModelState.IsValid)
            {
                string[] errors = ModelState.Values.SelectMany(v => v.Errors).Select(v => v.ErrorMessage).ToArray();
                return Json(new { errors = errors });
            }

            
            JsonResult result = Json("OK");
            switch (m)
            {
                case CRUD_ACTION.create:
                    //@TODO create
                    _manager.addPizza(model.Name,model.Description);
                    break;

                case CRUD_ACTION.update:
                    //@TODO update
                    _manager.setPizzaById(model.Id, model.Name, model.Description);
                    break;
                case CRUD_ACTION.delete:
                    //@TODO delete
                    _manager.deletePizza(_manager.getPizzaById(model.Id));
                    break;
                default:
                    return Json(new { errors = new string[] { "Operazione non permessa" } });
            }
            return result;
        }
    }
}

TestAppCore/TestAppCore/Views/Shared/_Layout.cshtml
@{ 
    Layout = "";
}
@inject IPizzaManager manager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestAppCore</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <style type="text/css">
        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

            .form-signin .form-control {
                position: relative;
                box-sizing: border-box;
                height: auto;
                padding: 10px;
                font-size: 16px;
            }

                .form-signin .form-control:focus {
                    z-index: 2;
                }

            .form-signin #inputName {
                /* margin-bottom: -1px; */
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }

            .form-signin #inputSurname {
                margin-bottom: 10px;
                border-radius: 0;
            }

        .custom-select {
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#"><img src="~/svgs/pizza.svg" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">Pizza Butt</a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-label="Toggle navigation" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarCollapse" style="">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Chi siamo</a>
                    </li>
                </ul>
                @if (ViewData["logged"] is null || ViewData["logged"] is false)
                {
                    <a class="nav-link text-light d-inline p-0" href="@Url.Action("login", "Login")">Login</a>
                }
                else
                {
                    <a class="nav-link text-light d-inline p-0" href="@Url.Action("pizzaManager", "Login")">Ciao Admin</a>
                }
            </div>
        </nav>
    </header>
    <main role="main">
        <div id="myCarousel" class="carousel slide mb-5" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class=""></li>
                <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item">
                    <img src="https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1355&q=80" style="width:100vw;height:80vh;">
                    <div class="container">
                        <div class="carousel-caption text-left">
                            <h1>La Margherita</h1>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a class="btn btn-lg btn-danger" href="#order" role="button">Gustala</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://images.unsplash.com/photo-1559978137-8c560d91e9e1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80" style="width:100vw;height:80vh;">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>La Napoli</h1>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a class="btn btn-lg btn-danger" href="#order" role="button">Provala Ora!</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item active">
                    <img src="https://images.unsplash.com/photo-1598023696416-0193a0bcd302?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1407&q=80" style="width:100vw;height:80vh;">
                    <div class="container">
                        <div class="carousel-caption text-right">
                            <h1>La marinara</h1>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a class="btn btn-lg btn-danger" href="#order" role="button">Ordina</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <div class="container marketing">

            <!-- Three columns of text below the carousel -->
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-4">
                    <form class="form-signin" action="/Order/OrderNow" method="post">
                        <a name="order"></a>
                        <img class="mb-4 mx-auto d-block" src="~/svgs/pizza.svg" alt="" width="72" height="72">
                        <h1 class="h3 mb-3 mx-auto font-weight-normal text-center">Ordina</h1>
                        <label for="inputName" class="sr-only">Nome</label>
                        <input type="text" id="inputName" name="inputName" class="form-control" placeholder="Nome" required="" autofocus="">
                        <label for="inputSurname" class="sr-only">Cognome</label>
                        <input type="text" id="inputSurname" name="inputSurname" class="form-control mb-0" placeholder="Cognome" required="">
                        <select class="custom-select" id="inputGroupSelect02" name="pizzaSelect">
                            <option selected>Seleziona una pizza</option>
                            @foreach (Pizza pizza in manager.getPizze())
                            {
                                <option value="@pizza.Name">@pizza.Name</option>
                            }

                        </select>
                        <br />
                        <button class="btn btn-lg btn-danger btn-block mt-4" type="submit">Ordina</button>
                    </form>
                </div>
            </div>
            @RenderBody()
            <hr class="featurette-divider">
        </div><!-- /.container -->
        
        <!-- FOOTER -->
        <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
            <p>© 2019-2020 Artea.com · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
        </footer>
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>